version: 2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

jobs:

  unittests:
    # docker:
    #   - image: circleci/python:2.7.15-stretch
    machine:
      enabled: true
      python:
        version: pypy-2.2.1
    steps:
      - checkout
      - run:
          name: download manager docker image
          command: wget http://repository.cloudifysource.org/cloudify/4.3.2/ga-release/cloudify-docker-manager-4.3.2ga.tar
      - run:
          name: load docker image
          command: docker load -i cloudify-docker-manager-4.3.2ga.tar
      - run:
          name: retain space by dumping the tar
          command: rm cloudify-docker-manager-4.3.2ga.tar
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host docker-cfy-manager:latest
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Runt flake8 test
          command: tox -e pep8
      - run:
          name: Run py27 test
          command: tox -e py27

workflows:
  version: 2
  tests:
    jobs:
      - unittests
